declare module "@dhis2/d2-i18n"
declare module "@dhis2/ui"
declare module "*.css"
declare module "*.js"
declare module "*.svg"
declare module "*.png"
declare module "react-select"
declare module "@material-ui/core"
